services:

  backend:
    build: .
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 2
        reservations:
          memory: 256M
          cpus: 1
    image: money-tracker/backend
    container_name: backend
    env_file:
      - path: .env
        required: true
    environment:
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

  nginx:
    image: nginx:1.26
    container_name: nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/certs/backend.crt:/etc/nginx/conf.d/backend.crt
      - ./config/certs/backend.csr:/etc/nginx/conf.d/backend.csr
      - ./config/certs/backend.key:/etc/nginx/conf.d/backend.key
      - ./config/certs/backend.pem:/etc/nginx/conf.d/backend.pem
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"

volumes:
  postgres_data:

networks:
  backend:
